# This service allows to set a control mode at runtime.
# The user can select control modes defined in iiwa_msgs/ControlMode and set the respective parameters accordingly to the selected mode.

iiwa_msgs/ControlMode control_mode
iiwa_msgs/JointImpedanceControlMode joint_impedance
iiwa_msgs/CartesianImpedanceControlMode cartesian_impedance
iiwa_msgs/CartesianSineImpedanceControlMode cartesian_sine_impedance
iiwa_msgs/DesiredForceControlMode disired_force
iiwa_msgs/SinePatternControlMode sine_pattern
iiwa_msgs/LissajousPatterControlMode lissajous_pattern
iiwa_msgs/SpiralPatternControlMode spiral_pattern
---
bool success
string error